# Generated by Django 4.2.4 on 2023-09-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_catego', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_catego', models.CharField(max_length=50)),
                ('descri', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='atualizado em ')),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
    ]
