# Generated by Django 4.2.4 on 2023-09-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id_item', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_item', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='atualizado em ')),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemsOrc',
            fields=[
                ('id_item_orc', models.IntegerField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='atualizado em ')),
            ],
            options={
                'db_table': 'items_orc',
                'managed': False,
            },
        ),
    ]
