# Generated by Django 4.2.4 on 2023-09-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='descri',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
