# Generated by Django 4.2.4 on 2023-09-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_items_descri'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsorc',
            name='qtd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='itemsorc',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
