import React from "react";

const tableDataContent = [
  {
    icon: <i className="fa fa-bar-chart" aria-hidden="true"></i>,
    First: "Mark",
    Last: "Otto",
    Handle: "@mdo",
    type: "default",
  },
  {
    First: "Jacob",
    Last: "Thornton",
    Handle: "@fat",
    type: "default",
  },
  {
    First: "Larry",
    Last: "the sky",
    title: "Default table",
    Handle: "@twitter",
    type: "default",
  },
  {
    First: "Mark",
    Last: "Otto",
    Handle: "@mdo",
    type: "default",
  },
  {
    First: "Jacob",
    Last: "Thornton",
    // title: "Table with hover",
    Handle: "@fat",
    type: "default",
  },
  {
    First: "Larry",
    Last: "the sky",
    Handle: "@twitter",
    type: "default",
  },
  {
    First: "Mark",
    Last: "Otto",
    Handle: "@mdo",
    type: "default",
  },
  {
    First: "Jacob",
    Last: "Thornton",
    // title: "Table with hover",
    Handle: "@fat",
    type: "default",
  },
  {
    First: "Larry",
    Last: "the sky",
    Handle: "@twitter",
    type: "default",
  },
  {
    First: "Mark",
    Last: "Otto",
    Handle: "@mdo",
    type: "default",
  },
  {
    First: "Jacob",
    Last: "Thornton",
    // title: "Table with hover",
    Handle: "@fat",
    type: "default",
  },
  {
    First: "Larry",
    Last: "the sky",
    Handle: "@twitter",
    type: "default",
  },
  {
    First: "Mark",
    Last: "Otto",
    Handle: "@mdo",
    type: "default",
  },
  {
    First: "Jacob",
    Last: "Thornton",
    // title: "Table with hover",
    Handle: "@fat",
    type: "default",
  },
  {
    First: "Larry",
    Last: "the sky",
    Handle: "@twitter",
    type: "default",
  },
  {
    First: "Mark",
    Last: "Otto",
    Handle: "@mdo",
    type: "default",
  },
  {
    First: "Jacob",
    Last: "Thornton",
    // title: "Table with hover",
    Handle: "@fat",
    type: "default",
  },
  {
    First: "Larry",
    Last: "the sky",
    Handle: "@twitter",
    type: "default",
  },
  {
    First: "Mark",
    Last: "Otto",
    Handle: "@mdo",
    type: "default",
  },
  {
    First: "Jacob",
    Last: "Thornton",
    // title: "Table with hover",
    Handle: "@fat",
    type: "default",
  },
  {
    First: "Larry",
    Last: "the sky",
    Handle: "@twitter",
    type: "default",
  },
  {
    First: "Mark",
    Last: "Otto",
    Handle: "@mdo",
    type: "default",
  },
  {
    First: "Jacob",
    Last: "Thornton",
    // title: "Table with hover",
    Handle: "@fat",
    type: "default",
  },
  {
    First: "Larry",
    Last: "the sky",
    Handle: "@twitter",
    type: "default",
  },
  {
    First: "Mark",
    Last: "Otto",
    Handle: "@mdo",
    type: "default",
  },
  {
    First: "Jacob",
    Last: "Thornton",
    // title: "Table with hover",
    Handle: "@fat",
    type: "default",
  },
  {
    First: "Larry",
    Last: "the sky",
    Handle: "@twitter",
    type: "default",
  },
  {
    icon: <i className="fa fa-bar-chart" aria-hidden="true"></i>,
    First: "hassan",
    Last: "the moon",
    Handle: "@google",
    type: "striped",
    title: "Table with hover",
  },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "striped" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "striped" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "striped" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "striped" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "striped" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "striped" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "striped" },
  {
    icon: <i className="fa fa-bar-chart" aria-hidden="true"></i>,
    First: "usman",
    Last: "the Bird",
    Handle: "@youtube",
    type: "light",
  },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "light" },
  {
    First: "usman",
    Last: "the Bird",
    Handle: "@youtube",
    type: "light",
    title: "Striped table",
  },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "light" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "light" },
  {
    icon: <i className="fa fa-bar-chart" aria-hidden="true"></i>,
    First: "usman",
    Last: "the Bird",
    Handle: "@youtube",
    type: "dark",
    title: "Dark table",
  },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },
  { First: "usman", Last: "the Bird", Handle: "@youtube", type: "dark" },

];

export default tableDataContent;
